### ISSUE TITLE
Scanning?

### ISSUE THREAD

**Issue by oleiman** [IanHarvey/bluepy#14]
Hey Ian,

Have you given much thought to adding low-energy scanning to bluepy? I saw it in your TODO's, and I'm wondering whether you have a sense of what it would take (time, roadblocks, etc). I've been considering taking this on and have done a bit of research, but, if you've already started, I'd like to pick your brain.

Thanks,
Oren

**Comment by OrenLederman** [comment]
Any updates on lescan? Can be very useful

**Comment by pcborenstein** [comment]
Why does lescan require sudo permission? You must have found a way around it already because you can't connect to a bluetooth device without scanning and finding it.

I've noticed the gatttool can connect to a device without sudo, but hcitool lecc does require sudo. Why is this? I assume answering the first question answers the second too...

**Comment by ShuffleBox** [comment]
If I remember correctly, if you add your user to the lp group, you should be able to.  
I didn't look to find the reason it's wired up to that group, but that was the solution when I was accessing a bluetooth adaptor as a regular user on Raspbian (raspberry pi2).  Worth a shot.

**Comment by IanHarvey** [comment]
As mentioned in issues #70 and issues #81, scanning is now implemented! There are no docs yet, and you still have to be root (or fiddle with **/dev/hciXX** permissions yourselves). 

Cheers
IH
