### ISSUE TITLE
python3.2 crash

### ISSUE THREAD

**Issue by dnastase** [IanHarvey/bluepy#19]
Hi, 

I have the following crash with python3.2:

Traceback (most recent call last):
  File "./home.py", line 8, in <module>
    import sensortag
  File "/home/pi/apps/bluepy/bluepy/sensortag.py", line 1, in <module>
    from btle import UUID, Peripheral
  File "/home/pi/apps/bluepy/bluepy/btle.py", line 344, in <module>
    UUID(0x1811, "Alert Notification Service"),
  File "/home/pi/apps/bluepy/bluepy/btle.py", line 58, in __init__
    self.binVal = binascii.a2b_hex(val)
TypeError: 'str' does not support the buffer interface

I think the following fixes it:

git diff
diff --git a/bluepy/btle.py b/bluepy/btle.py
index 7226c47..31b4328 100644
--- a/bluepy/btle.py
+++ b/bluepy/btle.py
@@ -55,7 +55,7 @@ class UUID:
         if len(val) <= 8:  # Short form
             val = ("0" * (8 - len(val))) + val + "00001000800000805F9B34FB"
 
-        self.binVal = binascii.a2b_hex(val)
+        self.binVal = binascii.a2b_hex(bytes(val, "ascii"))
         if len(self.binVal) != 16:
             raise ValueError(
                 "UUID must be 16 bytes, got '%s' (len=%d)" % (val,
@@ -175,7 +175,7 @@ class Peripheral:
             elif tval[0]=="h":
                 val = int(tval[1:], 16)
             elif tval[0]=='b':
-                val = binascii.a2b_hex(tval[1:])
+                val = binascii.a2b_hex(bytes(tval[1:], "ascii"))
             else:
                 raise BTLEException(BTLEException.INTERNAL_ERROR,
                              "Cannot understand response value %s" % repr(tval))

and it has no downside since you just use a2b_hex for data/numerical values.

**Comment by IanHarvey** [comment]
This is (IMO) a bug in 3.2 which was fixed in 3.3 - see the box at the top of https://docs.python.org/3.3/library/binascii.html

I don't intend to support 3.2 and earlier with the trunk bluepy. In particular, the lack of PEP 0414 in 3.2 makes it impossible to write portable code. I don't want to clutter the code unnecessarily, and I don't have the time to test on multiple Python 3.x versions.

I'd recommend you use Python 3.3 for running bluepy.

Thanks,
Ian
