### ISSUE TITLE
passive scan stops when connecting to bluetooth device

### ISSUE THREAD

**Issue by SHA89** [IanHarvey/bluepy#235]
i have 2 threads, 1 running passive scan, which should run forever, and 1 for setting up connections and executing tasks.
The moment i try to connect to the peripheral, my scanner stops.

Code to reproduce:

```python
import threading
import time

from bluepy.btle import Peripheral, Scanner

mac = "a0:e6:f8:ce:1a:02"


def do_scan():
    """ The scanning thread function """
    scanner = Scanner()
    scanner.scan(0, passive=True)
    print "Done scanning."

def do_connect():
    """ Connecting in main thread"""
    # sleep to give the scanner some startup time
    time.sleep(4)
    p = Peripheral()
    p.connect(mac)
    time.sleep(2)
    p.disconnect()

scan_thread = threading.Thread(target=do_scan)
scan_thread.setDaemon(True)
scan_thread.start()

do_connect()

```

**Comment by gandy92** [comment]
That is due to the bluetooth subsystem: Try running `hcitool lescan --passive` in one shell and issue a `gatttool -b MAC --char-read -a 0x0010` on one of the reported MAC addresses in another and the passive scan will terminate. So once you have disconnected from a device you will need to restart the scan.
